In [6]:
%pip install tabulate pandas

Requirement already satisfied: tabulate in /opt/homebrew/Cellar/jupyterlab/4.6.3/libexec/lib/python3.14/site-packages (0.10.0)
Collecting pandas
  Downloading pandas-3.0.5-cp314-cp314-macosx_11_0_arm64.whl.metadata (79 kB)
Collecting numpy>=2.3.3 (from pandas)
  Downloading numpy-2.5.2-cp314-cp314-macosx_14_0_arm64.whl.metadata (6.6 kB)
Requirement already satisfied: python-dateutil>=2.8.2 in /opt/homebrew/Cellar/jupyterlab/4.6.3/libexec/lib/python3.14/site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: six>=1.5 in /opt/homebrew/Cellar/jupyterlab/4.6.3/libexec/lib/python3.14/site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Downloading pandas-3.0.5-cp314-cp314-macosx_11_0_arm64.whl (10.0 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 10.0/10.0 MB 44.2 MB/s  0:00:00 eta 0:00:01
Downloading numpy-2.5.2-cp314-cp314-macosx_14_0_arm64.whl (5.4 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 5.4/5.4 MB 46.3 MB/s  0:00:00
Installing collected packages: numpy, pandas
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2/2 [pandas]━━━━ 1/2 [pandas]
Successfully installed numpy-2.5.2 pandas-3.0.5
Note: you may need to restart the kernel to use updated packages.

In [1]:
import pandas as pd

In [86]:
damage_per_rune_per_wave = 15
starting_mana = 115
passive_mana_per_wave = 20
rune_0_cost = (45 + 30 + 10) / 3.0
rune_inc_cost = 5 / 3.0

rune_costs = [rune_0_cost + i * rune_inc_cost for i in range(0, 100)]
rune_cum_cost = [sum(rune_costs[0:i + 1]) for i in range(0, 100)]

def find_last_index(arr, pred):
    return next((i for i in range(len(arr) - 1, -1, -1) if pred(arr[i])), -1)

def num_towers_for_mana_total(m):
    return 1 + find_last_index(rune_cum_cost, lambda c: c <= m)

def ratio_fn(total_hp, hpToNumRatio=0.7):
    numEnemies = round((total_hp / hpToNumRatio) ** 0.5) or 1
    enemyHp = round(total_hp / numEnemies) or 1
    return f"{numEnemies} @ {enemyHp}hp"

df = pd.DataFrame({'wave_index': range(0, 21)})
df['passive_mana_available'] = starting_mana + df['wave_index'] * passive_mana_per_wave
df['total_hp'] = 15 + 2.5 * df['wave_index'] ** 2;
df['approx_num'] = df['total_hp'].map(ratio_fn)
df['prev_wave_hp'] = df['total_hp'].shift(1).cumsum().fillna(0)
df['total_mana_available'] = df['passive_mana_available'] + df['prev_wave_hp']
df['num_runes'] = df['total_mana_available'].map(num_towers_for_mana_total)
df['damage_output'] = df['num_runes'] * damage_per_rune_per_wave

df['safety_factor'] = df['damage_output'] / df['total_hp']

df
# df[['total_hp', 'damage_output']]

,wave_index,passive_mana_available,total_hp,approx_num,prev_wave_hp,total_mana_available,num_runes,damage_output,safety_factor
0,0,115,15.0,5 @ 3hp,0.0,115.0,3,60,4.000000
1,1,135,17.5,5 @ 4hp,15.0,150.0,4,80,4.571429
2,2,155,25.0,6 @ 4hp,32.5,187.5,5,100,4.000000
3,3,175,37.5,7 @ 5hp,57.5,232.5,6,120,3.200000
4,4,195,55.0,9 @ 6hp,95.0,290.0,8,160,2.909091
5,5,215,77.5,11 @ 7hp,150.0,365.0,10,200,2.580645
6,6,235,105.0,12 @ 9hp,227.5,462.5,12,240,2.285714
7,7,255,137.5,14 @ 10hp,332.5,587.5,14,280,2.036364
8,8,275,175.0,16 @ 11hp,470.0,745.0,17,340,1.942857
9,9,295,217.5,18 @ 12hp,645.0,940.0,20,400,1.839080
10,10,315,265.0,19 @ 14hp,862.5,1177.5,24,480,1.811321
11,11,335,317.5,21 @ 15hp,1127.5,1462.5,28,560,1.763780
12,12,355,375.0,23 @ 16hp,1445.0,1800.0,32,640,1.706667
13,13,375,437.5,25 @ 18hp,1820.0,2195.0,37,740,1.691429
14,14,395,505.0,27 @ 19hp,2257.5,2652.5,42,840,1.663366
15,15,415,577.5,29 @ 20hp,2762.5,3177.5,47,940,1.627706
16,16,435,655.0,31 @ 21hp,3340.0,3775.0,52,1040,1.587786
17,17,455,737.5,32 @ 23hp,3995.0,4450.0,58,1160,1.572881
18,18,475,825.0,34 @ 24hp,4732.5,5207.5,64,1280,1.551515
19,19,495,917.5,36 @ 25hp,5557.5,6052.5,70,1400,1.525886
20,20,515,1015.0,38 @ 27hp,6475.0,6990.0,76,1520,1.497537

In [63]:
df2 = df[['total_hp']]

for hpToNumRatio in [.1, .2, .4, .6, .7, .8, .9, 1.0, 1.1, 1.2, 1.3, 1.5, 1.7, 2.0, 3.0, 5.0, 10.0, 20.0, 40.0, 100]:
    df2[f"h/n: {hpToNumRatio}"] = df2['total_hp'].map(lambda h: ratio_fn(h, hpToNumRatio))

df2

,total_hp,h/n: 0.1,h/n: 0.2,h/n: 0.4,h/n: 0.6,h/n: 0.7,h/n: 0.8,h/n: 0.9,h/n: 1.0,h/n: 1.1,...,h/n: 1.3,h/n: 1.5,h/n: 1.7,h/n: 2.0,h/n: 3.0,h/n: 5.0,h/n: 10.0,h/n: 20.0,h/n: 40.0,h/n: 100
0,15.0,12 @ 1hp,9 @ 2hp,6 @ 2hp,5 @ 3hp,5 @ 3hp,4 @ 4hp,4 @ 4hp,4 @ 4hp,4 @ 4hp,...,3 @ 5hp,3 @ 5hp,3 @ 5hp,3 @ 5hp,2 @ 8hp,2 @ 8hp,1 @ 15hp,1 @ 15hp,1 @ 15hp,1 @ 15hp
1,17.5,13 @ 1hp,9 @ 2hp,7 @ 2hp,5 @ 4hp,5 @ 4hp,5 @ 4hp,4 @ 4hp,4 @ 4hp,4 @ 4hp,...,4 @ 4hp,3 @ 6hp,3 @ 6hp,3 @ 6hp,2 @ 9hp,2 @ 9hp,1 @ 18hp,1 @ 18hp,1 @ 18hp,1 @ 18hp
2,25.0,16 @ 2hp,11 @ 2hp,8 @ 3hp,6 @ 4hp,6 @ 4hp,6 @ 4hp,5 @ 5hp,5 @ 5hp,5 @ 5hp,...,4 @ 6hp,4 @ 6hp,4 @ 6hp,4 @ 6hp,3 @ 8hp,2 @ 12hp,2 @ 12hp,1 @ 25hp,1 @ 25hp,1 @ 25hp
3,37.5,19 @ 2hp,14 @ 3hp,10 @ 4hp,8 @ 5hp,7 @ 5hp,7 @ 5hp,6 @ 6hp,6 @ 6hp,6 @ 6hp,...,5 @ 8hp,5 @ 8hp,5 @ 8hp,4 @ 9hp,4 @ 9hp,3 @ 12hp,2 @ 19hp,1 @ 38hp,1 @ 38hp,1 @ 38hp
4,55.0,23 @ 2hp,17 @ 3hp,12 @ 5hp,10 @ 6hp,9 @ 6hp,8 @ 7hp,8 @ 7hp,7 @ 8hp,7 @ 8hp,...,7 @ 8hp,6 @ 9hp,6 @ 9hp,5 @ 11hp,4 @ 14hp,3 @ 18hp,2 @ 28hp,2 @ 28hp,1 @ 55hp,1 @ 55hp
5,77.5,28 @ 3hp,20 @ 4hp,14 @ 6hp,11 @ 7hp,11 @ 7hp,10 @ 8hp,9 @ 9hp,9 @ 9hp,8 @ 10hp,...,8 @ 10hp,7 @ 11hp,7 @ 11hp,6 @ 13hp,5 @ 16hp,4 @ 19hp,3 @ 26hp,2 @ 39hp,1 @ 78hp,1 @ 78hp
6,105.0,32 @ 3hp,23 @ 5hp,16 @ 7hp,13 @ 8hp,12 @ 9hp,11 @ 10hp,11 @ 10hp,10 @ 10hp,10 @ 10hp,...,9 @ 12hp,8 @ 13hp,8 @ 13hp,7 @ 15hp,6 @ 18hp,5 @ 21hp,3 @ 35hp,2 @ 52hp,2 @ 52hp,1 @ 105hp
7,137.5,37 @ 4hp,26 @ 5hp,19 @ 7hp,15 @ 9hp,14 @ 10hp,13 @ 11hp,12 @ 11hp,12 @ 11hp,11 @ 12hp,...,10 @ 14hp,10 @ 14hp,9 @ 15hp,8 @ 17hp,7 @ 20hp,5 @ 28hp,4 @ 34hp,3 @ 46hp,2 @ 69hp,1 @ 138hp
8,175.0,42 @ 4hp,30 @ 6hp,21 @ 8hp,17 @ 10hp,16 @ 11hp,15 @ 12hp,14 @ 12hp,13 @ 13hp,13 @ 13hp,...,12 @ 15hp,11 @ 16hp,10 @ 18hp,9 @ 19hp,8 @ 22hp,6 @ 29hp,4 @ 44hp,3 @ 58hp,2 @ 88hp,1 @ 175hp
9,217.5,47 @ 5hp,33 @ 7hp,23 @ 9hp,19 @ 11hp,18 @ 12hp,16 @ 14hp,16 @ 14hp,15 @ 14hp,14 @ 16hp,...,13 @ 17hp,12 @ 18hp,11 @ 20hp,10 @ 22hp,9 @ 24hp,7 @ 31hp,5 @ 44hp,3 @ 72hp,2 @ 109hp,1 @ 218hp
10,265.0,51 @ 5hp,36 @ 7hp,26 @ 10hp,21 @ 13hp,19 @ 14hp,18 @ 15hp,17 @ 16hp,16 @ 17hp,16 @ 17hp,...,14 @ 19hp,13 @ 20hp,12 @ 22hp,12 @ 22hp,9 @ 29hp,7 @ 38hp,5 @ 53hp,4 @ 66hp,3 @ 88hp,2 @ 132hp
11,317.5,56 @ 6hp,40 @ 8hp,28 @ 11hp,23 @ 14hp,21 @ 15hp,20 @ 16hp,19 @ 17hp,18 @ 18hp,17 @ 19hp,...,16 @ 20hp,15 @ 21hp,14 @ 23hp,13 @ 24hp,10 @ 32hp,8 @ 40hp,6 @ 53hp,4 @ 79hp,3 @ 106hp,2 @ 159hp
12,375.0,61 @ 6hp,43 @ 9hp,31 @ 12hp,25 @ 15hp,23 @ 16hp,22 @ 17hp,20 @ 19hp,19 @ 20hp,18 @ 21hp,...,17 @ 22hp,16 @ 23hp,15 @ 25hp,14 @ 27hp,11 @ 34hp,9 @ 42hp,6 @ 62hp,4 @ 94hp,3 @ 125hp,2 @ 188hp
13,437.5,66 @ 7hp,47 @ 9hp,33 @ 13hp,27 @ 16hp,25 @ 18hp,23 @ 19hp,22 @ 20hp,21 @ 21hp,20 @ 22hp,...,18 @ 24hp,17 @ 26hp,16 @ 27hp,15 @ 29hp,12 @ 36hp,9 @ 49hp,7 @ 62hp,5 @ 88hp,3 @ 146hp,2 @ 219hp
14,505.0,71 @ 7hp,50 @ 10hp,36 @ 14hp,29 @ 17hp,27 @ 19hp,25 @ 20hp,24 @ 21hp,22 @ 23hp,21 @ 24hp,...,20 @ 25hp,18 @ 28hp,17 @ 30hp,16 @ 32hp,13 @ 39hp,10 @ 50hp,7 @ 72hp,5 @ 101hp,4 @ 126hp,2 @ 252hp
15,577.5,76 @ 8hp,54 @ 11hp,38 @ 15hp,31 @ 19hp,29 @ 20hp,27 @ 21hp,25 @ 23hp,24 @ 24hp,23 @ 25hp,...,21 @ 28hp,20 @ 29hp,18 @ 32hp,17 @ 34hp,14 @ 41hp,11 @ 52hp,8 @ 72hp,5 @ 116hp,4 @ 144hp,2 @ 289hp
16,655.0,81 @ 8hp,57 @ 11hp,40 @ 16hp,33 @ 20hp,31 @ 21hp,29 @ 23hp,27 @ 24hp,26 @ 25hp,24 @ 27hp,...,22 @ 30hp,21 @ 31hp,20 @ 33hp,18 @ 36hp,15 @ 44hp,11 @ 60hp,8 @ 82hp,6 @ 109hp,4 @ 164hp,3 @ 218hp
17,737.5,86 @ 9hp,61 @ 12hp,43 @ 17hp,35 @ 21hp,32 @ 23hp,30 @ 25hp,29 @ 25hp,27 @ 27hp,26 @ 28hp,...,24 @ 31hp,22 @ 34hp,21 @ 35hp,19 @ 39hp,16 @ 46hp,12 @ 61hp,9 @ 82hp,6 @ 123hp,4 @ 184hp,3 @ 246hp
18,825.0,91 @ 9hp,64 @ 13hp,45 @ 18hp,37 @ 22hp,34 @ 24hp,32 @ 26hp,30 @ 28hp,29 @ 28hp,27 @ 31hp,...,25 @ 33hp,23 @ 36hp,22 @ 38hp,20 @ 41hp,17 @ 49hp,13 @ 63hp,9 @ 92hp,6 @ 138hp,5 @ 165hp,3 @ 275hp
19,917.5,96 @ 10hp,68 @ 13hp,48 @ 19hp,39 @ 24hp,36 @ 25hp,34 @ 27hp,32 @ 29hp,30 @ 31hp,29 @ 32hp,...,27 @ 34hp,25 @ 37hp,23 @ 40hp,21 @ 44hp,17 @ 54hp,14 @ 66hp,10 @ 92hp,7 @ 131hp,5 @ 184hp,3 @ 306hp
20,1015.0,101 @ 10hp,71 @ 14hp,50 @ 20hp,41 @ 25hp,38 @ 27hp,36 @ 28hp,34 @ 30hp,32 @ 32hp,30 @ 34hp,...,28 @ 36hp,26 @ 39hp,24 @ 42hp,23 @ 44hp,18 @ 56hp,14 @ 72hp,10 @ 102hp,7 @ 145hp,5 @ 203hp,3 @ 338hp